// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: ws_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Channel int32

const (
	Channel_GPS_REALTIME Channel = 0
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "GPS_REALTIME",
	}
	Channel_value = map[string]int32{
		"GPS_REALTIME": 0,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_ws_message_proto_enumTypes[0].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_ws_message_proto_enumTypes[0]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_ws_message_proto_rawDescGZIP(), []int{0}
}

type Request struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Channel   Channel                `protobuf:"varint,1,opt,name=channel,proto3,enum=websocket.Channel" json:"channel,omitempty"`
	RequestId string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Request_Publish
	//	*Request_Subscribe
	//	*Request_Unsubscribe
	Payload       isRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_ws_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_ws_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_ws_message_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_GPS_REALTIME
}

func (x *Request) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Request) GetPayload() isRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetPublish() *PublishMessage {
	if x != nil {
		if x, ok := x.Payload.(*Request_Publish); ok {
			return x.Publish
		}
	}
	return nil
}

func (x *Request) GetSubscribe() *SubscribeMessage {
	if x != nil {
		if x, ok := x.Payload.(*Request_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *Request) GetUnsubscribe() *UnsubscribeMessage {
	if x != nil {
		if x, ok := x.Payload.(*Request_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_Publish struct {
	Publish *PublishMessage `protobuf:"bytes,3,opt,name=publish,proto3,oneof"`
}

type Request_Subscribe struct {
	Subscribe *SubscribeMessage `protobuf:"bytes,4,opt,name=subscribe,proto3,oneof"`
}

type Request_Unsubscribe struct {
	Unsubscribe *UnsubscribeMessage `protobuf:"bytes,5,opt,name=unsubscribe,proto3,oneof"`
}

func (*Request_Publish) isRequest_Payload() {}

func (*Request_Subscribe) isRequest_Payload() {}

func (*Request_Unsubscribe) isRequest_Payload() {}

type PublishMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMessage) Reset() {
	*x = PublishMessage{}
	mi := &file_ws_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMessage) ProtoMessage() {}

func (x *PublishMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ws_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMessage.ProtoReflect.Descriptor instead.
func (*PublishMessage) Descriptor() ([]byte, []int) {
	return file_ws_message_proto_rawDescGZIP(), []int{1}
}

func (x *PublishMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SubscribeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indexes       []int64                `protobuf:"varint,1,rep,packed,name=indexes,proto3" json:"indexes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeMessage) Reset() {
	*x = SubscribeMessage{}
	mi := &file_ws_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeMessage) ProtoMessage() {}

func (x *SubscribeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ws_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeMessage.ProtoReflect.Descriptor instead.
func (*SubscribeMessage) Descriptor() ([]byte, []int) {
	return file_ws_message_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeMessage) GetIndexes() []int64 {
	if x != nil {
		return x.Indexes
	}
	return nil
}

type UnsubscribeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indexes       []int64                `protobuf:"varint,1,rep,packed,name=indexes,proto3" json:"indexes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeMessage) Reset() {
	*x = UnsubscribeMessage{}
	mi := &file_ws_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeMessage) ProtoMessage() {}

func (x *UnsubscribeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ws_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeMessage.ProtoReflect.Descriptor instead.
func (*UnsubscribeMessage) Descriptor() ([]byte, []int) {
	return file_ws_message_proto_rawDescGZIP(), []int{3}
}

func (x *UnsubscribeMessage) GetIndexes() []int64 {
	if x != nil {
		return x.Indexes
	}
	return nil
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Response_Response
	//	*Response_Broadcast
	Payload       isResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_ws_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_ws_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_ws_message_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetPayload() isResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetResponse() *ResponseMessage {
	if x != nil {
		if x, ok := x.Payload.(*Response_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Response) GetBroadcast() *BroadcastMessage {
	if x != nil {
		if x, ok := x.Payload.(*Response_Broadcast); ok {
			return x.Broadcast
		}
	}
	return nil
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_Response struct {
	Response *ResponseMessage `protobuf:"bytes,1,opt,name=response,proto3,oneof"`
}

type Response_Broadcast struct {
	Broadcast *BroadcastMessage `protobuf:"bytes,2,opt,name=broadcast,proto3,oneof"`
}

func (*Response_Response) isResponse_Payload() {}

func (*Response_Broadcast) isResponse_Payload() {}

type ResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StatusCode    uint32                 `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMessage) Reset() {
	*x = ResponseMessage{}
	mi := &file_ws_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMessage) ProtoMessage() {}

func (x *ResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ws_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMessage.ProtoReflect.Descriptor instead.
func (*ResponseMessage) Descriptor() ([]byte, []int) {
	return file_ws_message_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResponseMessage) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ResponseMessage) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ResponseMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BroadcastMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       Channel                `protobuf:"varint,1,opt,name=channel,proto3,enum=websocket.Channel" json:"channel,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastMessage) Reset() {
	*x = BroadcastMessage{}
	mi := &file_ws_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessage) ProtoMessage() {}

func (x *BroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ws_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessage.ProtoReflect.Descriptor instead.
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return file_ws_message_proto_rawDescGZIP(), []int{6}
}

func (x *BroadcastMessage) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_GPS_REALTIME
}

func (x *BroadcastMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MessageBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          [][]byte               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBatch) Reset() {
	*x = MessageBatch{}
	mi := &file_ws_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBatch) ProtoMessage() {}

func (x *MessageBatch) ProtoReflect() protoreflect.Message {
	mi := &file_ws_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBatch.ProtoReflect.Descriptor instead.
func (*MessageBatch) Descriptor() ([]byte, []int) {
	return file_ws_message_proto_rawDescGZIP(), []int{7}
}

func (x *MessageBatch) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_ws_message_proto protoreflect.FileDescriptor

const file_ws_message_proto_rawDesc = "" +
	"\n" +
	"\x10ws_message.proto\x12\twebsocket\"\x98\x02\n" +
	"\aRequest\x12,\n" +
	"\achannel\x18\x01 \x01(\x0e2\x12.websocket.ChannelR\achannel\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x125\n" +
	"\apublish\x18\x03 \x01(\v2\x19.websocket.PublishMessageH\x00R\apublish\x12;\n" +
	"\tsubscribe\x18\x04 \x01(\v2\x1b.websocket.SubscribeMessageH\x00R\tsubscribe\x12A\n" +
	"\vunsubscribe\x18\x05 \x01(\v2\x1d.websocket.UnsubscribeMessageH\x00R\vunsubscribeB\t\n" +
	"\apayload\"$\n" +
	"\x0ePublishMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\",\n" +
	"\x10SubscribeMessage\x12\x18\n" +
	"\aindexes\x18\x01 \x03(\x03R\aindexes\".\n" +
	"\x12UnsubscribeMessage\x12\x18\n" +
	"\aindexes\x18\x01 \x03(\x03R\aindexes\"\x8c\x01\n" +
	"\bResponse\x128\n" +
	"\bresponse\x18\x01 \x01(\v2\x1a.websocket.ResponseMessageH\x00R\bresponse\x12;\n" +
	"\tbroadcast\x18\x02 \x01(\v2\x1b.websocket.BroadcastMessageH\x00R\tbroadcastB\t\n" +
	"\apayload\"\x8a\x01\n" +
	"\x0fResponseMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\rR\n" +
	"statusCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"T\n" +
	"\x10BroadcastMessage\x12,\n" +
	"\achannel\x18\x01 \x01(\x0e2\x12.websocket.ChannelR\achannel\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\"\n" +
	"\fMessageBatch\x12\x12\n" +
	"\x04data\x18\x01 \x03(\fR\x04data*\x1b\n" +
	"\aChannel\x12\x10\n" +
	"\fGPS_REALTIME\x10\x00B\aZ\x05./;pbb\x06proto3"

var (
	file_ws_message_proto_rawDescOnce sync.Once
	file_ws_message_proto_rawDescData []byte
)

func file_ws_message_proto_rawDescGZIP() []byte {
	file_ws_message_proto_rawDescOnce.Do(func() {
		file_ws_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ws_message_proto_rawDesc), len(file_ws_message_proto_rawDesc)))
	})
	return file_ws_message_proto_rawDescData
}

var file_ws_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ws_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ws_message_proto_goTypes = []any{
	(Channel)(0),               // 0: websocket.Channel
	(*Request)(nil),            // 1: websocket.Request
	(*PublishMessage)(nil),     // 2: websocket.PublishMessage
	(*SubscribeMessage)(nil),   // 3: websocket.SubscribeMessage
	(*UnsubscribeMessage)(nil), // 4: websocket.UnsubscribeMessage
	(*Response)(nil),           // 5: websocket.Response
	(*ResponseMessage)(nil),    // 6: websocket.ResponseMessage
	(*BroadcastMessage)(nil),   // 7: websocket.BroadcastMessage
	(*MessageBatch)(nil),       // 8: websocket.MessageBatch
}
var file_ws_message_proto_depIdxs = []int32{
	0, // 0: websocket.Request.channel:type_name -> websocket.Channel
	2, // 1: websocket.Request.publish:type_name -> websocket.PublishMessage
	3, // 2: websocket.Request.subscribe:type_name -> websocket.SubscribeMessage
	4, // 3: websocket.Request.unsubscribe:type_name -> websocket.UnsubscribeMessage
	6, // 4: websocket.Response.response:type_name -> websocket.ResponseMessage
	7, // 5: websocket.Response.broadcast:type_name -> websocket.BroadcastMessage
	0, // 6: websocket.BroadcastMessage.channel:type_name -> websocket.Channel
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_ws_message_proto_init() }
func file_ws_message_proto_init() {
	if File_ws_message_proto != nil {
		return
	}
	file_ws_message_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_Publish)(nil),
		(*Request_Subscribe)(nil),
		(*Request_Unsubscribe)(nil),
	}
	file_ws_message_proto_msgTypes[4].OneofWrappers = []any{
		(*Response_Response)(nil),
		(*Response_Broadcast)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ws_message_proto_rawDesc), len(file_ws_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_message_proto_goTypes,
		DependencyIndexes: file_ws_message_proto_depIdxs,
		EnumInfos:         file_ws_message_proto_enumTypes,
		MessageInfos:      file_ws_message_proto_msgTypes,
	}.Build()
	File_ws_message_proto = out.File
	file_ws_message_proto_goTypes = nil
	file_ws_message_proto_depIdxs = nil
}
